# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 413bbf54000fbc946b7560a9b32491dad5636e37ba82d0b15ea0e227aaf7ee1b320adcbd31cb9f5cd984e4b07e5100bda76eb306558806fcca28f3e957cafc73

test:
  secret_key_base: 1934a7ea263ef00a2e757a56e0ae84d2e58a6a6e52785b2dae3c31a05ee9a3d112a8921f5ae1e9d3cfab22713a55219b472a2468fe4ba5e335fda3ee38f629d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
